### ISSUE TITLE
Error while encode

### ISSUE THREAD

**Issue by MusfickBytevity** [bepsvpt/blurhash#10]
When using
$blurHash = BlurHash::encode($uploadedFile);

Error showing
ErrorException: exif_imagetype(C:\xampp\tmp): Failed to open stream: Permission denied in file C:\Users\User\Desktop\....\vendor\bepsvpt\blurhash\src\Drivers\GdDriver.php on line 58

Laravel 11
PHP 8.2.4

**Comment by bepsvpt** [comment]
This issue is fixed by 4506cdd50608789a157e828e2f7832a71836caac.
