### ISSUE TITLE
Using with php-vips

### ISSUE THREAD

**Issue by binaryfire** [bepsvpt/blurhash#7]
Great package!

My app has a media library feature and I’m using php-vips to automatically generate multiple sizes for each upload.

It’s a multi tenant app so I need to keep resource usage low (vips is _much_ faster and more efficient than gd).

Is there a way I can use this package without triggering any Intervention processing? I only need to generate the blurhash. I’m using JS for decoding.

What if I use vips to generate an image that’s smaller than the max width setting?

**Comment by bepsvpt** [comment]
Hello @binaryfire,

Abstracting the image library is a good idea, I plan to research it later. However, due to my current workload, it may take some time before I can develop it, and I cannot provide a time estimate at the moment.

**Comment by bepsvpt** [comment]
The `php-vips` driver is included in version 3. However, I've encountered a performance issue when decoding from a blurhash string. The `libvips` and `php-vips` documentation were too vague for further improvements.

**Comment by binaryfire** [comment]
Hey @bepsvpt, thanks for adding this! Will do some testing as soon as I have time.
