### ISSUE TITLE
Issues with package when uploading to the live host

### ISSUE THREAD

**Issue by azulmouad** [bepsvpt/blurhash#9]
The code works good at localhost and generate the hash code
But when i upload the code Laravel to my Hosting, when i try to get hash key image i got this issues:

```
<!--
Error: Class &quot;Bepsvpt\Blurhash\Blurhash&quot; not found in file /home/u452756940/domains/example.ma/public_html/ose/app/Http/Controllers/Controller.php on line 23

#0 /home/u452756940/domains/example.ma/public_html/ose/app/Http/Controllers/FeedController.php(36): App\Http\Controllers\Controller-&gt;blurHashImage()
#1 /home/u452756940/domains/example.ma/public_html/ose/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\FeedController-&gt;createFeed()
#2 /home/u452756940/domains/example.ma/public_html/ose/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller-&gt;callAction()
```

My composer.json:
 ```
"require": {
        "php": "^8.1",
        "bepsvpt/blurhash": "^2.1.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "Bepsvpt\\Blurhash\\": "vendor/bepsvpt/blurhash/src/"
        }
    },
```

i tried composer update still same issues

**Comment by bepsvpt** [comment]
If local testing goes smoothly, I suspect it might be an issue with file system case sensitivity. Could you tell me what the operating systems are for your local and online environments?

**Comment by azulmouad** [comment]
Thanks for your prompt response. I've looked into the issue, and here are the details regarding the operating systems in my local and online environments:

Local Environment (MacBook Pro 2019)
Online Environment (Hostinger Server)

**Comment by bepsvpt** [comment]
> Error: Class "Bepsvpt\Blurhash\Blurhash" not found in file

Based on the error message you shared, it looks like there's a mix-up with the case in `Bepsvpt\Blurhash\Blurhash`. The correct one should be `Bepsvpt\Blurhash\BlurHash`. Can you take a look and see if that's the issue?

**Comment by azulmouad** [comment]
The issue is now resolved. 
The correct class is `Bepsvpt\Blurhash\BlurHash`, and everything is working as expected.

Thank you!
